### ISSUE TITLE
Uncaught TypeError: Cannot read property 'childNodes' of null

### ISSUE THREAD

**Issue by vincentschroeder** [winkerVSbecks/xvg#23] opened 2017-01-12 15:05 UTC
I just installed the extension every svg I want look at let this error message popup in the console: `content.js:218 Uncaught TypeError: Cannot read property 'childNodes' of null`
When I click on the xvg icon a second error appears as you can see in the screenshot. 

I am using Chrome Version 49.0.2623.87 (64-bit) on MacOS Sierra 10.12.1 

![svg-bug-screenshot](https://cloud.githubusercontent.com/assets/6410444/21894948/4e16a134-d8e1-11e6-8637-12c0b39f3413.png)

**Comment by winkerVSbecks** [comment] 2017-01-12 17:11
duplicate of #18

**Closed by winkerVSbecks** 2017-01-12 17:11 UTC
